# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required SearXNG settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - searxng_uid
    - searxng_gid
    - searxng_hostname
    - searxng_path_prefix
    - searxng_container_network
    - searxng_config_server_secret_key

- name: Run if Traefik is enabled
  when: searxng_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for SearXNG are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - searxng_container_labels_traefik_hostname
        - searxng_container_labels_traefik_path_prefix

    - name: Fail if searxng_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          searxng_container_labels_traefik_path_prefix (`{{ searxng_container_labels_traefik_path_prefix }}`) must be `/`.
          SearXNG does not support hosting under a subpath yet.
      when: "searxng_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `searxng_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if searxng_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          searxng_container_labels_traefik_path_prefix (`{{ searxng_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/searxng`).
      when: "searxng_container_labels_traefik_path_prefix != '/' and searxng_container_labels_traefik_path_prefix[-1] == '/'"
